<<<<<<< HEAD
spring.application.name=Hotel_booking_System

spring.datasource.url=jdbc:mysql://localhost:3306/hotel_booking_db
spring.datasource.username=root
spring.datasource.password=Vicky@1802

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Security API Config
letsgo.app.jwtSecret=${JWT_SECRET:letsgo_default_secret_key_123456789_at_least_32_chars}
letsgo.app.jwtExpirationMs=86400000
=======
spring.datasource.url=jdbc:mysql://localhost:3306/hotel_booking_db
spring.datasource.username=root
spring.datasource.password=root123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
>>>>>>> 15e776cc0b35aff375187a4598d9380bbe126f7b
